# Repository
repo_name: FundacaoJoaoPinheiro/estatpublicas
repo_url: https://github.com/FundacaoJoaoPinheiro/estatpublicas
edit_uri: edit/main/docs/

# Project information
site_name: EstatPúblicas
site_url: https://sitename.example
site_author: Grupo de Pesquisa em Estatísticas Públicas
site_description: >-
  Pesquisa na produção de estatísticas

nav:
  - Início: index.md
  - Pesquisadores: pesquisadores/index.md
  - Projetos: projetos/index.md
  - Publicações: http://repositorio.fjp.mg.gov.br/handle/123456789/4255

theme:
  name: material
  language: pt
  font:
    text: Lato
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/chart-line
  favicon: assets/red_bar_chart_icon.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: red
      accent: pink
extra:
  favicon: images/favicon.ico
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FundacaoJoaoPinheiro
    - icon: fontawesome/brands/r-project
      link: https://rpubs.com/fjp

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
